In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [7]:
!ls
%cd CameraFacePropre/
!ls

AlphaPose_MAH02084.mp4	CameraFacePropre	MAH02094.MP4
bareme.txt		Gym-trainer_2.mp4	MAH02102.MP4
BDD_CamFace		Gym-trainer_lowres.mp4	Openpose_MAH02084.mp4
brutes			MAH02084.MP4
/content/gdrive/My Drive/Gym_trainer/Videos_basesDeDonnées/CameraFacePropre
P01  P03  P05  P07  P09  P11  P13  P15	P17  P18-19-20-21.Mp4.30fps  P20
P02  P04  P06  P08  P10  P12  P14  P16	P18  P19		     P21


In [9]:
PATH = "./gdrive/My Drive/Gym_trainer/Videos_basesDeDonnées/CameraFacePropre"
PATH="."

import os
import numpy as np

files = os.listdir(PATH)
print(files)

file = open(PATH+'Y.txt', "r")
y_train = []
for line in file:
  line = line[:-1]
  line = line.replace(",", ".")
  y_train.append(float(line))

y_train = y_train/(np.max(y_train))
x_train = []

files.sort()
print(files)
#files.pop("Test_RNN.ipynb")
for f in files:
  if f[-3:] == 'npy':
    m = np.load(PATH+f)
    #print(f)
    m = m.reshape(-1)
    x_train.append(m)
    #print(m.shape)
x_train = np.array(x_train)
print((x_train.shape))
#_train[140:].shape

['P03', 'P08', 'P04', 'P06', 'P09', 'P07', 'P01', 'P02', 'P05', 'P10', 'P16', 'P14', 'P20', 'P18', 'P17', 'P11', 'P13', 'P12', 'P19', 'P15', 'P21', 'P18-19-20-21.Mp4.30fps']


FileNotFoundError: ignored

In [0]:
#x_train = np.array(x_train)


y_test = y_train[140:]
x_test = x_train[140:]

#x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1],1))
#x_test = np.reshape(x_test, (x_test.shape[0],x_test.shape[1],1))

y_train2 = y_train[:140]
x_train2 = x_train[:140]

In [0]:
x_train

array([[  0.   ,   0.   ,   0.   , ..., 189.481, 189.5  , 188.819],
       [  0.   ,   0.   ,   0.   , ..., 184.297, 184.274, 181.061],
       [  0.   ,   0.   ,   0.   , ..., 185.585, 186.893, 185.596],
       ...,
       [  0.   , 199.862, 200.554, ...,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   , ..., 169.371, 169.365, 167.399],
       [  0.   ,   0.   ,   0.   , ...,   0.   ,   0.   , 211.571]])

In [0]:
input_shape = x_train2[0].shape
input_shape

(5000,)

In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

import collections
import matplotlib.pyplot as plt
import numpy as np

import tensorflow as tf

from tensorflow.keras import layers

In [0]:
model = tf.keras.Sequential()
# Add an Embedding layer expecting input vocab of size 1000, and
# output embedding dimension of size 64.
model.add(layers.Embedding(input_dim=5000, output_dim=25))

# Add a LSTM layer with 128 internal units.
model.add(layers.LSTM(128))

# Add a Dense layer with 10 units and softmax activation.
model.add(layers.Dense(1))

model.summary()



Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 25)          125000    
_________________________________________________________________
lstm (LSTM)                  (None, 128)               78848     
_________________________________________________________________
dense (Dense)                (None, 1)                 129       
Total params: 203,977
Trainable params: 203,977
Non-trainable params: 0
_________________________________________________________________
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        

In [0]:
model.compile(optimizer='adam', loss='mse', metrics=['mse'])

In [0]:
x_train2

array([[  0.   ,   0.   ,   0.   , ..., 189.481, 189.5  , 188.819],
       [  0.   ,   0.   ,   0.   , ..., 184.297, 184.274, 181.061],
       [  0.   ,   0.   ,   0.   , ..., 185.585, 186.893, 185.596],
       ...,
       [  0.   ,   0.   ,   0.   , ..., 184.283, 184.934, 184.309],
       [  0.   ,   0.   ,   0.   , ..., 203.12 , 200.513, 199.879],
       [225.188, 225.207, 220.646, ..., 196.006, 195.33 , 194.657]])

In [0]:
input_data = [x_train2, y_train2]
target_data = [x_test, y_test]

#model.fit(x_train2, y_train2, batch_size=1, epochs = 10)

model.fit(x_train2, y_train2, validation_data=(x_test, y_test), batch_size=1,epochs=1)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 140 samples, validate on 36 samples
140/140 [==============================] - 1301s 9s/sample - loss: 0.0908 - mean_squared_error: 0.0908 - val_loss: 0.0060 - val_mean_squared_error: 0.0060


array([[ 0.02191032, -0.04744357,  0.04562105, ...,  0.06636793,
         0.04680658,  0.0260597 ],
       [ 0.02499045, -0.04436344,  0.04870118, ...,  0.06944806,
         0.04988671,  0.02913982],
       [-0.03339695, -0.10275083, -0.00968622, ...,  0.01106067,
        -0.00850069, -0.02924757],
       ...,
       [ 0.05120993, -0.01814395,  0.07492066, ...,  0.09566755,
         0.0761062 ,  0.05535931],
       [ 0.01116783, -0.05818605,  0.03487856, ...,  0.05562545,
         0.0360641 ,  0.01531721],
       [ 0.06087828, -0.0084756 ,  0.08458901, ...,  0.1053359 ,
         0.08577455,  0.06502766]])

array([0.87136929, 0.94072318, 0.84765857, 0.91167753, 0.88915234,
       0.92649674, 0.87136929, 0.85536455, 0.8861885 , 0.93953764,
       0.93538826, 0.93360996, 0.89389449, 0.85655009, 0.85240071,
       0.88915234, 0.91286307, 0.88915234, 0.75577949, 0.94842916,
       0.84647303, 0.84054535, 0.89389449, 0.82868998, 0.85536455,
       0.8358032 , 0.90100771, 0.8879668 , 0.82987552, 0.74570243,
       0.85536455, 0.82868998, 0.8731476 , 0.82691168, 0.84647303,
       0.86721992])

In [0]:
model2 = tf.keras.Sequential()
# Add an Embedding layer expecting input vocab of size 1000, and
# output embedding dimension of size 64.
#model = Sequential()
model2.add(layers.Dense(512, input_shape=(5000,), activation = 'relu'))
model2.add(layers.Dense(512, activation = 'relu'))
model2.add(layers.Dense(512, activation = 'relu'))
model2.add(layers.Dense(256, activation = 'relu'))
model2.add(layers.Dense(25, activation = 'relu'))
# Add a Dense layer with 10 units and softmax activation
model2.add(layers.Dense(1, activation = 'linear'))

#model2.summary()
model2.compile(optimizer='adam', loss='mse', metrics=['mse'])
model2.fit(x_train2, y_train2, validation_data=(x_test, y_test), batch_size=1,epochs=20)

Train on 140 samples, validate on 36 samples
Epoch 1/20
140/140 [==============================] - 1s 7ms/sample - loss: 0.0138 - mean_squared_error: 0.0138 - val_loss: 0.0186 - val_mean_squared_error: 0.0186
Epoch 2/20
140/140 [==============================] - 1s 5ms/sample - loss: 0.0141 - mean_squared_error: 0.0141 - val_loss: 0.0186 - val_mean_squared_error: 0.0186
Epoch 3/20
140/140 [==============================] - 1s 6ms/sample - loss: 0.0141 - mean_squared_error: 0.0141 - val_loss: 0.0186 - val_mean_squared_error: 0.0186
Epoch 4/20
140/140 [==============================] - 1s 6ms/sample - loss: 0.0141 - mean_squared_error: 0.0141 - val_loss: 0.0186 - val_mean_squared_error: 0.0186
Epoch 5/20
140/140 [==============================] - 1s 6ms/sample - loss: 0.0141 - mean_squared_error: 0.0141 - val_loss: 0.0186 - val_mean_squared_error: 0.0186
Epoch 6/20
140/140 [==============================] - 1s 6ms/sample - loss: 0.0141 - mean_squared_error: 0.0141 - val_loss: 0.0186 - va